services:
  - type: web
    name: api-lova
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton_host_mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: client_1
      - key: DB_USERNAME
        value: ton_user
      - key: DB_PASSWORD
        value: ton_password